# -*- coding: utf-8 -*-
"""FileHanding.ipynb

Automatically generated by Colaboratory.

Original file is located at
        https://colab.research.google.com/drive/1IlOzVLIencRpCBqRj7tfWPXZvESLtw0D
"""

import os
import time

def create_file():
    print('Создаю файл File.txt ...')
    with open("File.txt", "w+") as f:
        f.write("Съешь еще этих мягких французских булочек и выпей чаю \n  \
                Eat some more of those soft french buns and have some tea \n \
                Eat some more of those soft french buns and have some tea \n \
                Eat some more of those soft french buns and have some tea"
        )
    time.sleep(1)
    print('Создали файл File.txt !')
    path = os.path.abspath('File.txt')
    return path


def file_name(path):
        print(os.path.basename(path))


def file_size(path):
        print("Байт: ",os.path.getsize(path))


def repeat_word(text):
    repeat_word = input("Enter your word ")
    counter = text.count(repeat_word)
    print(counter)


def long_and_short(arr):
    sorted_list = sorted(arr, key=len)
    print('Самое короткое - ', sorted_list[0], 'Самое длинное - ', sorted_list[-1])


def quantity_words(arr):
    print('Количество слов -', len(arr))


def dictionary(arr):
    diction = {}
    for i in range(len(arr)):
        diction[arr[i]] = len(arr[i])
    print(diction)


def writing(path):
    with open(path, "a") as file:
     file.write('\n Eat some more of those soft french buns and have some tea')


def delete_word(text):
    word_for_delete = input("Введите слово которое нужно удалить ")
    text = text.replace(word_for_delete, "")
    print(text)


def main():
    path = str()
    all_words = []

    print("Do you want to create file?\n1 - yes\n2 - no")
    var = int(input())
    if (var == 1):
        path = create_file()
    else:
        print('Пропишите путь к файлу')
        path = input()


    while True:
      print("--------------------------------\n1 - имя файла \n2 - размер файла \n3 - самое длинное и короткое слово \n4 - кол-во слов \n5 - словарь \n6 - запись в файл \n7 - удаление повторений слова \n8 - кол-во повторений\n0 - Выход из программы\n--------------------------------")
      num_f = int(input())
      # print(path)

      with open(path, mode="r") as f:
          text = f.read()
          all_words = text.split()

      match num_f:
          case 1:
              file_name (path)
          case 2:
              file_size(path)
          case 3:
              long_and_short(all_words)
          case 4:
              quantity_words (all_words)
          case 5:
              dictionary(all_words)
          case 6:
              writing (path)
          case 7:
              delete_word (text)
          case 8:
              repeat_word(text)
          case 0:
              exit()


if __name__ == '__main__':
    main()